feat: introduce dashboard
tankicagoneva/launchpad-explorer pull request #6
Opened 2024-10-21 18:20 UTC by tankicagoneva

The page title has been updated to "Launchpad Explorer".

The routing has been updated to include a new Launch page. 

New components have been added, including LaunchInformation, Badge, Card, LaunchCounter, LaunchDetails, and useLaunchDetails and useLaunchpadsDetails hooks. 

The launch and launchpad types have been refactored. 

Additionally, documentation has been updated.

2024-10-23 17:52 UTC, LjupcheVasilev requested changes

2024-10-26 21:03 UTC, tankicagoneva commented on app/src/hooks/useLaunchDetails .ts
> +  return { launchDetails };
Немам искуство со тоа, пробав ама не ми успеа. Нека остане сега за сега така па може да го разговараме на следниот состанок ако се согласуваш 😊

2024-10-29 02:30 UTC, LjupcheVasilev commented on app/src/hooks/useLaunchDetails .ts
> +  return { launchDetails };
Важи нема проблем

2024-10-29 02:35 UTC, LjupcheVasilev commented on app/src/hooks/useLaunchDetails .ts
> +        } catch (error) {
Уште оваа останало другото се е океј

2024-10-30 15:34 UTC, LjupcheVasilev approved these changes

2024-10-30 21:00 UTC, merged